# POV Sphere Mosaic, square pattern
# Program for conversion of image into a set of tightly packed rectangular boxes, colored according to source image pixels
# (c) Ilya Razmanov (ilyarazmanov@gmail.com)
# History:
# 2007  Initial AmphiSoft POV Sphere Mosaic, using FilterMeister https://filtermeister.com/
# 2023  Rewritten to Python. I/O with PyPNG from: https://gitlab.com/drj11/pypng
# 2024  Complete internal rewriting. Versions from now on:
#
# 01.000    b4-zaika.py Initial release
# 01.001    Changed box z-size to source brightness minus 5% randomized
#
#       Project mirrors:
#       https://github.com/Dnyarri/POVmosaic
#       https://gitflic.ru/project/dnyarri/povmosaic
#

import time
import random
import png
from tkinter import filedialog

# Open source image
sourcefilename = filedialog.askopenfilename(title='Open source PNG file', filetypes=[('PNG','.png')], defaultextension = ('PNG','.png'))
if (sourcefilename == ''):
    quit()

source = png.Reader(filename = sourcefilename)  # starting PyPNG

X,Y,pixels,info = source.asRGBA() # Opening image, iDAT comes to "pixels" as bytearray, to be tuple'd later

totalpixels = X*Y               # Total number OF pixels, not PIXEL NUMBER
rowlength = X*(info['planes'])  # Row length
Z = (info['planes'])            # Maximum CHANNEL NUMBER
imagedata = tuple((pixels))     # Attempt to fix all bytearrays as tuple

if (info['bitdepth'] == 8):
    maxcolors = 255             # Maximal value for 8-bit channel
if (info['bitdepth'] == 16):
    maxcolors = 65535           # Maximal value for 16-bit channel

# Open export file
resultfile = filedialog.asksaveasfile(mode='w', title='Save resulting POV file', filetypes = 
            [
			('POV-Ray scene file', '*.pov'),
            ('All Files', '*.*'),],
    defaultextension = ('POV-Ray scene file','.pov'))
if (resultfile == ''):
    quit()
# Both files opened

# src a-la FM style src(x,y,z)
# Image should be opened as "imagedata" by main program before
# Note that X, Y, Z are not determined in function, you have to determine it in main program

def src(x, y, z):  # Analog src from FM, force repeate edge instead of out of range

    cx = x; cy = y
    cx = max(0,cx); cx = min((X-1),cx)
    cy = max(0,cy); cy = min((Y-1),cy)

    position = (cx*Z) + z   # Here is the main magic of turning two x, z into one array position
    channelvalue = int(((imagedata[cy])[position]))
    
    return channelvalue
# end of src function

def srcY(x, y):  # Converting to greyscale, returns Y, force repeate edge instead of out of range

    cx = x; cy = y
    cx = max(0,cx); cx = min((X-1),cx)
    cy = max(0,cy); cy = min((Y-1),cy)

    if (info['planes'] < 3):    # supposedly L and LA
        Yntensity = src(x, y, 0)
    else:                       # supposedly RGB and RGBA
        Yntensity = int(0.2989*src(x, y, 0) + 0.587*src(x, y, 1) + 0.114*src(x, y, 2))
    
    return Yntensity
# end of srcY function

#	WRITING POV FILE

# ------------
#  POV header
# ------------

resultfile.write('// Persistence of Vision Ray Tracer Scene Description File\n')
resultfile.write('// Vers: 3.5\n')
resultfile.write('// Description: A mosaic picture consisting from a solid boxes\n')
resultfile.write('// Auth: Automatically generated by POV Sphere Mosaic program, based on AmphiSoft POV Sphere Mosaic plug-in \n\n')
resultfile.write('// Project mirrors:\n')
resultfile.write('// https://github.com/Dnyarri/POVmosaic\n')
resultfile.write('// https://gitflic.ru/project/dnyarri/POVmosaic\n')
resultfile.write('// developed by Ilya Razmanov\n// (ilyarazmanov@gmail.com)\n\n')
resultfile.write(f'// Converted from: {sourcefilename} ')
seconds = time.time()
localtime = time.ctime(seconds)
resultfile.write(f'at: {localtime}\n')
resultfile.write(f'// Source info: {info}\n\n')

#  Statements

resultfile.write('#version 3.5;\n\n')
resultfile.write('global_settings\n')
resultfile.write('{\n')
resultfile.write('  max_trace_level 3\n')
resultfile.write('  adc_bailout 0.01\n')
resultfile.write('  ambient_light <0.5,0.5,0.5>\n')
resultfile.write('  assumed_gamma 1.0\n')
resultfile.write('}\n\n')

# Standard includes
resultfile.write('#include "colors.inc"\n\n')

# Thingie element

resultfile.write('// Thingie and related parameters\n')
resultfile.write('#declare thingie = box { <-0.5, -0.5, 0.0>, <0.5, 0.5, 1.0>}\n') # Box size 1.0
resultfile.write('#declare thingie_finish = finish{ambient .1 diffuse .7 specular .8 roughness .001}\n')
resultfile.write('#declare color_factor = 1.5;  // Color multiplier for all channels\n')
resultfile.write('#declare zsize_factor = 1.0;  // z-Scale multiplier for all thingies\n\n')

# Object "thething" made of thingies

resultfile.write('#declare thething = union {\n')  # Opening object "thething"

# Now going to cycle through image and build onject

for y in range(0, Y, 1):

    resultfile.write(f'\n\n// Row {y}\n')

    for x in range(0, X, 1):

        r = float(src(x,y,0))/maxcolors; g = float(src(x,y,1))/maxcolors; b = float(src(x,y,2))/maxcolors    # Normalize colors to 0..1.0
        a = float(src(x,y,3))/maxcolors     # a = 0 - transparent, a = 1.0 - opaque
        tobeornottobe = random.random()     # to be used for alpha dithering
        yarkost = float(0.2989*r)+float(0.587*g)+float(0.114*b) # brightness
        zsize = 1.0                         # original cube. All edits below may be commented out
        zsize = yarkost * zsize             # edited for thingie z-scaling according to source brighness
        zsize = zsize - 0.05*yarkost*random.random()     # furher adding random to z-scaling, keeping 0..1 range

        if (a > tobeornottobe):           # whether to draw thingie in place of partially transparent pixel or not
            resultfile.write('object {thingie ')    # Opening object "thingie" to draw
            resultfile.write(f'scale <1,1,{zsize}> translate <{x}, {y}, 0>')
            resultfile.write(' pigment {')
            resultfile.write(f'rgb <color_factor*{r}, color_factor*{g}, color_factor*{b}>')
            resultfile.write('}')
            resultfile.write(' finish {')
            resultfile.write('thingie_finish')
            resultfile.write('}')
            resultfile.write('}\n')                 # Closing object "thingie" after modifications

# Transform object to fit 1, 1, 1 cube at 0, 0, 0 coordinates
resultfile.write('\n// Object transforms to fit 1, 1, 1 cube at 0, 0, 0 coordinates\n')
resultfile.write('translate <0.5, 0.5, 0>\n')   # compensate for -0.5 extra, now object fit 0..X, 0..Y, 0..maxcolors
resultfile.write(f'scale <-1.000000/{max(X,Y)}, -1.000000/{max(X,Y)}, 1.000000*zsize_factor>\n')  # rescale, mirroring POV coordinates to match Photoshop coordinate system
resultfile.write(f'translate <0.5 * {X/max(X,Y)}, 0.5 * {Y/max(X,Y)}, 0>\n\n')  # translate to center object bottom at x = 0, y = 0, z = 0

resultfile.write('}\n')   # Closing object "thething"

# Insert object into scene
resultfile.write('object {thething}\n')

# Camera
proportions = max(X,Y)/X
resultfile.write('#declare camera_height = 3.0;\n\n')
resultfile.write('camera {\n   // orthographic\n    location <0.0, 0.0, camera_height>\n    right x*image_width/image_height\n    up y\n    direction <0,0,1>\n    angle 2.0*(degrees(atan2(')
resultfile.write(f'{0.5 * proportions}')
resultfile.write(', camera_height-zsize_factor))) // Supposed to fit object \n    look_at <0.0, 0.0, 0.0>\n}\n\n')

# Light 1
resultfile.write('light_source {0*x\n   color rgb <1.1,1,1>\n   translate <4, 2, 3>\n}\n\n')
# Light 2
resultfile.write('light_source {0*x\n   color rgb <0.9,1,1>\n   translate <-3, -4, 2>\n}\n\n')
resultfile.write('// - END -')
# Close output
resultfile.close()