/* 
POVRay include file
Description: Preset file for scene generated with 63zaika.py

    Rotated cubes that, from vertical view point, look like hexagones.

https://github.com/Dnyarri/POVmosaic
Read project help.html for options description.
Author: Ilya Razmanov
 {#008800, 0} */

#declare yes_color = 1;

#declare thingie = box{<-0.5, -0.5, -0.5>, <0.5, 0.5, 0.5>
    rotate <45, 45, 0> scale 0.86
  }