/* 
POVRay include file
Description: Preset file for scene generated with 3zaika.py
https://github.com/Dnyarri/POVmosaic
Read project help.html for options description.
*/

#include "icosa.inc"        // Verify .inc file path for your system
#declare thingie = icosa    // Adds non-standard object from external file "icosa.inc"
#declare thingie_finish = thingie_finish_3
#declare f_value = 0.5;
#declare rotate_rnd = <90, 90, 90>;